name: CItesting

on: [push]

jobs:
  # Label of the runner job
  runner-job:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
      keycloak:
        image: quay.io/keycloak/keycloak:latest
        env:
          KC_DB: postgres
          KC_DB_URL: jdbc:postgresql://localhost:5432/keycloak
          KC_DB_USERNAME: postgres
          KC_DB_PASSWORD: postgres
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin
          KC_HEALTH_ENABLED: true
          KC_METRICS_ENABLED: true
          KC_HTTP_PORT: 8100
          KC_HTTPS_PORT: 8101
          KC_LOG_LEVEL: INFO
          KC_FILE: /opt/keycloak/data/import/keycloak-test-realm.json
        ports:
          # Maps tcp port 5432 on service container to the host
          - 8100:8100
          - 8101:8101
        volumes:
          - "./keycloak-test-realm.json:/opt/keycloak/data/import/keycloak-test-realm.json"
    steps:
    - name: Show Keycloak logs
      run: docker logs $(docker ps -a -q -
    - uses: actions/checkout@v3
    - name: Show Docker containers
      run: docker ps
    - name: show listening ports
      run: sudo netstat -tulpn
    - name: Run keycloak healthcheck
      run: ./keycloak-healthcheck.sh