name: CItesting

on: [push]

jobs:
  # Label of the runner job
  runner-job:
    # You must use a Linux environment when using service containers or container jobs
    runs-on: ubuntu-latest

    services:
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
      keycloak:
        image: quay.io/keycloak/keycloak:latest
        env:
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin
          KC_HEALTH_ENABLED: true
          KC_METRICS_ENABLED: true
        ports:
          # Maps tcp port 5432 on service container to the host
          - 8100:8100
          - 8101:8101
        volumes:
          - "./keycloak-test-realm.json:/opt/keycloak/data/import/keycloak-test-realm.json"
        options: --entrypoint "/opt/keycloak/bin/kc.sh start-dev --auto-build --http-port=8100 --https-port=8101 --log-level=INFO --db=postgres --features=token-exchange --db-url=jdbc:postgresql://db:5432/keycloak --db-username=postgres --db-password=postgres --import-realm"

    steps:
    - name: Show Keycloak logs
      run: docker logs $(docker ps -a -q --filter ancestor=quay.io/keycloak/keycloak:latest --format="{{.ID}}")
    - uses: actions/checkout@v3
    - name: Show Docker containers
      run: docker ps
    - name: show listening ports
      run: sudo netstat -tulpn
    - name: Run keycloak healthcheck
      run: ./keycloak-healthcheck.sh